### PR TITLE
Add link to retweet to top_retweets

### PR DESCRIPTION
**Pull request by peter-hank**
https://cyber.harvard.edu/projectmanagement/issues/17118

@thatandromeda can you take a look and see if you can fix the specs issue? Thanks.

### CODE REVIEW

**Comment by peter-hank** [comment]
@thatandromeda can you take a look?

`eval` is not nice, but `Rails` doesn't really want to return `hstore` as a `Hash` for some reason, even with `store_accessor`.

**Comment by thatandromeda** [comment]
I'm looking at this and I'm confused as to what the `store_accessor` is doing at all. The existing code was able to operate on hstores -- if, for instance, `ds` is a DataSet, and I do `ds.top_words`, I get a hash back, which I can use in the normal hashlike ways, even though I have not defined a `top_words` accessor. What are you trying to accomplish with this code that the original was not accomplishing?

**Comment by thatandromeda** [comment]
For example, here's me with some sample data in my rails console.

Screen Shot 2020-03-20 at 9 30 14 AM

**Comment by peter-hank** [comment]
@thatandromeda it doesn't seem to return nested hashes as I need to:
- `{ "lol": 5, "lol2": 45 }` will work fine
- `{ "lol": { count: 5, link: "http://lol.com" }, "lol2": { count: 45, link: "http://lol2.com" } }` will return the nested parts as `String` not `Hash`

**Comment by thatandromeda** [comment]
Ah! Awesome, I get it. Thanks. I'll think on this for a bit.

**Comment by thatandromeda** [comment]
OK, so I am wondering if we want to be using a different data structure.

Idea 1: Maybe we want a local Retweet object, and what we're storing in the DB is a list of serializations of it, and we rehydrate the serializations from the DB into Retweets.

Idea 2: Maybe we don't want to be storing nested hashes -- maybe we want to be storing nested arrays, and relying on the ordering property of arrays. So instead of `{ "lol": { count: 5, link: "http://lol.com" }`, we could do `{ "lol", 5, "http://lol.com" }`.

Idea 2 is a little YOLO (we're relying on ourselves to do it right rather than having protections of type-checking) but I expect simpler to implement. Does either of those work for you?

**Comment by peter-hank** [comment]
@thatandromeda #2 looks good to me, let me try update it.

**Comment by peter-hank** [comment]
@thatandromeda actually #1, can you take a look?

**Comment by thatandromeda** [comment]
Awesome. I got these tests passing, did some surgery on the git history to tidy it up.

**Comment by peter-hank** [comment]
Nice, thanks!

**Pull request merged**
